
builds:
  -
    binary: lporg
    goos:
      - darwin
    goarch:
      - amd64
    ldflags: -s -w -X main.Version={{.Version}} -X main.BuildTime={{.Date}}

archives:
  - id:
    format: tar.gz
    replacements:
      amd64: amd64
      darwin: macOS

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^bumping"
      - "^Update"
      - "reorg"
      - "updates"
      - Merge pull request
      - Merge branch

checksum:
  name_template: "checksums.txt"

signs:
  - artifacts: checksum
  
brews:
  - ids:
    github:
      owner: blacktop
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/blacktop/lporg"
    description: "Organize Your macOS Launchpad Apps."
    test: |
      system "#{bin}/lporg --version"