before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: darwin
    binary: lporg
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: -s -w -X main.Version={{.Version}} -X main.BuildTime={{.Date}}
universal_binaries:
  - id: darwin
    replace: true
    name_template: "lporg"
archives:
  - replacements:
      darwin: macOS
      amd64: x86_64
      all: universal
    name_template: "lporg_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - completions/*
checksum:
  name_template: "checksums.darwin.txt"
  disable: false
signs:
  - artifacts: checksum
snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - name: lporg
    tap:
      owner: blacktop
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/blacktop/lporg"
    description: Organize Your macOS Launchpad Apps
    install: |
      bin.install "lporg"
    test: |
      system "#{bin}/lporg --version"
rigs:
  - name: lporg
    rig:
      owner: blacktop
      name: fish-food
    homepage: https://github.com/blacktop/lporg
    description: Organize Your macOS Launchpad Apps
    license: MIT
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^bumping"
      - "^Update"
      - "reorg"
      - "updates"
      - Merge pull request
      - Merge branch
release:
  footer: |
    ## What to do next?
    - Follow us on [Twitter](https://twitter.com/blacktop__);
