
name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: macos-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "stable"
      id: go

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Test Default
      run: go run main.go -V default --no-backup --yes
    - name: Test Save
      run: go run main.go -V save --config /tmp/lp.yml
    - name: Test Load
      run: go run main.go -V load --config /tmp/lp.yml --no-backup --yes
    - name: Test Version
      run: go run main.go version